<?php
/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */

$configInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Config\ScopeConfigInterface');

// @see Baze_LockAddresses
$accessVar = $configInterface->getValue('customer/address/address_book_access', 'store');
if ($accessVar === null) $accessVar = 1; // If var absent, assume Accessible
$editVar = $configInterface->getValue('customer/address/address_book_editable', 'store');
if ($editVar === null) $editVar = 1; // If var absent, assume Editable

if($accessVar == 1) {
?>
<div class="block block-dashboard-addresses">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Address Book')) ?></strong>
        <a class="action edit" href="<?= $block->escapeUrl($block->getAddressBookUrl()) ?>"><span><?= $block->escapeHtml(__('Manage Addresses')) ?></span></a>
    </div>
    <div class="block-content">
        <div class="box box-billing-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryBillingAddressHtml() ?>
                </address>
            </div>
            <?php if($editVar == 1) { ?>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>" data-ui-id="default-billing-edit-link"><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
                </div>
            <?php } ?>
        </div>
        <div class="box box-shipping-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryShippingAddressHtml() ?>
                </address>
            </div>
            <?php if($editVar == 1) { ?>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>" data-ui-id="default-shipping-edit-link"><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<?php } ?>
